# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            BHD
tagline:          'Engineering the Web by Samuel Hudson'
description:      'I am a software engineer from London, UK. I currently work at <a href="http://www.thefoundry.co.uk/">The Foundry</a>, building applications for the vfx and design industry. Follow <a href="http://twitter.com/samsamm">@samsamm</a>'
url:              http://www.blackholedigital.com
baseurl:          /

author:
  name:           'Samuel Hudson'
  url:            https://twitter.com/samsamm

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/samsamm777
