# Site settings
title: Black Hole Digital
email: contact@blackholedigital.com
url: https://www.blackholedigital.com
description: "Black Hole Digital is an independant game studio from london, uk. Working on space exploration market economy trading game Sector:72."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#800000'

# Footer settings
footer: Black Hole Digital

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/blackholedigital
  - title: facebook
    url: https://facebook.com/blackholedigital

# Build settings
markdown: kramdown
permalink: pretty

paginate: 5
paginate_path: "/blog/page:num/"

gems: [jekyll-paginate]