# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Black Hole Digital
tagline:          'Engineering the Web by Samuel Hudson'
description:      'I am a software engineer from London, UK. I currently work at <a href="http://www.thefoundry.co.uk/">The Foundry</a>, building applications for the vfx and design industry. Follow <a href="http://twitter.com/samsamm">@samsamm</a>'
url:              http://www.blackholedigital.com

author:
  name:           'Samuel Hudson'
  url:            https://twitter.com/samsamm

paginate:         5

# Custom vars
version:          1.0.0

social:
  twitter:        https://twitter.com/samsamm
  facebook:       https://facebook.com/samueldavidhudson
  instagram:      https://instagram.com/samsamm777
  github:         https://github.com/samsamm777
  linkedin:       http://www.linkedin.com/pub/samuel-hudson/58/a48/500
